sudo: required
language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

jdk:
  - oraclejdk8

addon:
  sonarcloud: true

script:
  - npm test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=manuvaldes9 -Dsonar.projectKey=ci-cd-reactjs -Dsonar.sources='./app' -X
  - docker build -t manuvaldes9/ci-cd-reactjs .
  - docker tag manuvaldes9/ci-cd-reactjs registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    # push to dockerhub
    docker push manuvaldes9/ci-cd-reactjs;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME;

  on:
    branch: master