sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  # install deps
  - yarn install
script:
  - yarn test
  - yarn build
  # build docker images
  - docker build -t manuvaldes9/ci-cd-reactjs .
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push manuvaldes9/ci-cd-reactjs;
  branch: master