sudo: required
language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jdk:
  - oraclejdk8

addons:
  sonarcloud: true

script:
  - npm test
  - docker build -t manuvaldes9/ci-cd-reactjs .
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=manuvaldes9-github -Dsonar.projectKey=ci-cd-reactjs -Dsonar.sources='./app' -X

deploy:
  provider: script
  script:   
    docker push manuvaldes9/ci-cd-reactjs;
  on:
    branch: main